global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: "cloudops_app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
